version: "3.7"

services:

##########

    node:
        container_name: eshop_node
        
        build: 
            context: docker/node/
            cache_from:
                - cached_nuxt

        volumes:
            - $PWD/client:/var/www/client

        ports: 
            - 3000:3000

        environment:
            - HOST=0.0.0.0

##########

    php:
        container_name: eshop_php

        build:  docker/php-fpm/

        volumes:
            -  ./server:/var/www/server

        depends_on:
            -  postgres
            -  redis

        env_file:
            - .env

##########

    nginx:    
        container_name: eshop_nginx     

        build:  docker/nginx/

        volumes:       
            - ./server:/var/www/server
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/sites/:/etc/nginx/sites-available
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d

        depends_on:
            - php
            - node

        ports:  
            - "80:80"
            - "81:81"
            - "82:82"

##########

    postgres:  
        container_name: eshop_postgres

        build: docker/postgres/

        volumes:
            - database:/var/lib/postgresql/data
            - ./docker/dev/postgres/dumps/:/tmp/  

        ports:  
            - 54321:5432

        environment:
            - LC_ALL=C.UTF-8
            - POSTGRES_DB=docker 
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker

##########

    redis:
        container_name: eshop_redis

        build: docker/redis/

        volumes:  
            - redis:/data

        ports:
            - 63791:6379

##########
    
    supervisor:
        container_name: eshop_visor

        build: docker/supervisor/

        volumes:
            - ./:/var/www/
            - ./docker/supervisor/conf.d:/etc/supervisor/conf.d
            - ./docker/supervisor/logs:/var/log

        depends_on:
            - postgres
            - redis

########## Volumes ##########

volumes:
    database:
        driver: local
    redis:
        driver: local